In [1]:
import pandas as pd
import numpy as np

In [2]:
items = pd.read_csv("../../Kaggle Data/Movie Lens/ml-100k/u.item",sep='|',names=['movieid','movie title','release date','video release date',
              'IMDb URL', 'unknown','Action','Adventure','Animation',
              'Children\'s', 'Comedy', 'Crime','Documentary','Drama','Fantasy',
              'Film-Noir','Horror','Musical','Mystery','Romance' ,'Sci-Fi','Thriller','War','Western'],encoding='latin-1')
test = pd.read_csv("../../Kaggle Data/Movie Lens/ml-100k/u1.test",sep='\t',names=['userid','movieid','ratings','timestamp'],encoding='latin-1')
user = pd.read_csv("../../Kaggle Data/Movie Lens/ml-100k/u1.base",sep='\t',names=['userid','movieid','ratings','timestamp'],encoding='latin-1')

In [3]:
user.head()

   userid  movieid  ratings  timestamp
0       1        1        5  874965758
1       1        2        3  876893171
2       1        3        4  878542960
3       1        4        3  876893119
4       1        5        3  889751712

In [4]:
items.head()

,movieid,movie title,release date,video release date,IMDb URL,unknown,Action,Adventure,Animation,Children's,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,Toy Story (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Toy%20Story%2...,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
1,2,GoldenEye (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?GoldenEye%20(...,0,1,1,0,0,...,0,0,0,0,0,0,0,1,0,0
2,3,Four Rooms (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Four%20Rooms%...,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,4,Get Shorty (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Get%20Shorty%...,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,Copycat (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Copycat%20(1995),0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [5]:
user_items_merged = user.merge(items, on = 'movieid',how='inner')
user_test_merged = test.merge(items,on='movieid',how='inner')

In [6]:
user_items_subset = user_items_merged[['movie title','userid','ratings']]
user_test_subset = user_test_merged[['movie title','userid','ratings']]

In [7]:
user_items_subset.head()

        movie title  userid  ratings
0  Toy Story (1995)       1        5
1  Toy Story (1995)       2        4
2  Toy Story (1995)       6        4
3  Toy Story (1995)      13        3
4  Toy Story (1995)      16        5

In [8]:
user_items_subset.describe()

            userid       ratings
count  80000.00000  80000.000000
mean     525.16570      3.528350
std      255.94956      1.118565
min        1.00000      1.000000
25%      334.00000      3.000000
50%      535.00000      4.000000
75%      744.00000      4.000000
max      943.00000      5.000000

In [9]:
#user_items_subset.pivot(values = 'ratings',columns = 'movie title')
pivoted_user_items = user_items_subset.pivot_table(values='ratings', index= 'userid', columns='movie title',fill_value = 0)[:50]
pivoted_user_test = user_test_subset.pivot_table(values='ratings', index= 'userid', columns='movie title',fill_value = 0)[:50]

In [10]:
pivoted_user_items.head()

movie title,'Til There Was You (1997),1-900 (1994),101 Dalmatians (1996),12 Angry Men (1957),187 (1997),2 Days in the Valley (1996),"20,000 Leagues Under the Sea (1954)",2001: A Space Odyssey (1968),3 Ninjas: High Noon At Mega Mountain (1998),"39 Steps, The (1935)",...,Wyatt Earp (1994),Year of the Horse (1997),You So Crazy (1994),Young Frankenstein (1974),Young Guns (1988),Young Guns II (1990),"Young Poisoner's Handbook, The (1995)",Zeus and Roxanne (1997),unknown,Á köldum klaka (Cold Fever) (1994)
userid,,,,,,,,,,,,,,,,,,,,,
1,0,0,0,5,0,0,3,4,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,4,0,0,...,0,0,0,4,0,0,0,0,0,0

In [11]:
pivoted_user_test.head()

movie title,'Til There Was You (1997),1-900 (1994),101 Dalmatians (1996),12 Angry Men (1957),187 (1997),2 Days in the Valley (1996),"20,000 Leagues Under the Sea (1954)",2001: A Space Odyssey (1968),3 Ninjas: High Noon At Mega Mountain (1998),"39 Steps, The (1935)",...,"Wrong Trousers, The (1993)",Wyatt Earp (1994),Yankee Zulu (1994),Year of the Horse (1997),Young Frankenstein (1974),Young Guns (1988),Young Guns II (1990),"Young Poisoner's Handbook, The (1995)",Zeus and Roxanne (1997),unknown
userid,,,,,,,,,,,,,,,,,,,,,
1,0,0,2,0,0,0,0,0,0,0,...,0,0,0,0,5,3,0,0,0,4
2,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,2,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,4

In [12]:
def distance_metrics(vec1, vec2 , metrics):
    if metrics == 'euclidean':
        result = np.sqrt(np.sum((vec1-vec2)**2))
    elif metrics == 'manhattan':
        result = np.sum(np.abs(vec1-vec2))
    return result

In [13]:
def find_similar_users(self,movie_not_seen,k):
    movies_rated_k_users = {}
    for movie in movie_not_seen:
        user_subset_seen_movie = pivoted_user_items[pivoted_user_items[movie] > 0]
        similarity_matrix = []
        for other in user_subset_seen_movie.index:
            similarity_matrix.append((distance_metrics(pivoted_user_items.loc[self],pivoted_user_items.loc[other],'euclidean'),other))
        movies_rated_k_users[movie] = np.mean([[pivoted_user_items.loc[users[1],movie] for users in sorted(similarity_matrix)][1:k+1]])
    return movies_rated_k_users

In [14]:
similar_users = {}
for self in pivoted_user_items.index:
    movie_not_seen = pivoted_user_items.columns[pivoted_user_items.loc[self,pivoted_user_items.columns] == 0]
    similar_users[self] = find_similar_users(self,movie_not_seen,10)
    print("Ratings for user {} predicted".format(self))

/home/prerit/.local/lib/python3.5/site-packages/numpy/core/_methods.py:59: RuntimeWarning: Mean of empty slice.
  warnings.warn("Mean of empty slice.", RuntimeWarning)
/home/prerit/.local/lib/python3.5/site-packages/numpy/core/_methods.py:70: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)

Ratings for user 1 predicted
Ratings for user 2 predicted
Ratings for user 3 predicted
Ratings for user 4 predicted
Ratings for user 5 predicted
Ratings for user 6 predicted
Ratings for user 7 predicted
Ratings for user 8 predicted
Ratings for user 9 predicted
Ratings for user 10 predicted
Ratings for user 11 predicted
Ratings for user 12 predicted
Ratings for user 13 predicted
Ratings for user 14 predicted
Ratings for user 15 predicted
Ratings for user 16 predicted
Ratings for user 17 predicted
Ratings for user 18 predicted
Ratings for user 19 predicted
Ratings for user 20 predicted
Ratings for user 21 predicted
Ratings for user 22 predicted
Ratings for user 23 predicted
Ratings for user 24 predicted
Ratings for user 25 predicted
Ratings for user 26 predicted
Ratings for user 27 predicted
Ratings for user 28 predicted
Ratings for user 29 predicted
Ratings for user 30 predicted
Ratings for user 31 predicted
Ratings for user 32 predicted
Ratings for user 33 predicted
Ratings for user 34 predicted
Ratings for user 35 predicted
Ratings for user 36 predicted
Ratings for user 37 predicted
Ratings for user 38 predicted
Ratings for user 39 predicted
Ratings for user 40 predicted
Ratings for user 41 predicted
Ratings for user 42 predicted
Ratings for user 43 predicted
Ratings for user 44 predicted
Ratings for user 45 predicted
Ratings for user 46 predicted
Ratings for user 47 predicted
Ratings for user 48 predicted
Ratings for user 49 predicted
Ratings for user 50 predicted

In [18]:
# k most similar users for every movie not seen by each user.
predictions = pd.DataFrame(similar_users).fillna(0).T

In [19]:
predictions

,'Til There Was You (1997),1-900 (1994),101 Dalmatians (1996),12 Angry Men (1957),187 (1997),2 Days in the Valley (1996),"20,000 Leagues Under the Sea (1954)",2001: A Space Odyssey (1968),3 Ninjas: High Noon At Mega Mountain (1998),"39 Steps, The (1935)",...,Wyatt Earp (1994),Year of the Horse (1997),You So Crazy (1994),Young Frankenstein (1974),Young Guns (1988),Young Guns II (1990),"Young Poisoner's Handbook, The (1995)",Zeus and Roxanne (1997),unknown,Á köldum klaka (Cold Fever) (1994)
1,0.0,0.0,2.333333,0.00,0.0,0.0,0.00,0.000,0.0,4.0,...,0.0,0.0,0.0,4.4,0.0,0.0,2.0,0.0,0.0,0.0
2,0.0,0.0,2.666667,4.25,0.0,0.0,3.25,4.375,0.0,4.0,...,0.0,0.0,0.0,4.4,0.0,0.0,2.0,0.0,0.0,0.0
3,0.0,0.0,2.333333,4.25,0.0,0.0,3.25,4.375,0.0,4.0,...,0.0,0.0,0.0,4.4,0.0,0.0,2.0,0.0,0.0,0.0
4,0.0,0.0,2.333333,4.25,0.0,0.0,3.25,4.375,0.0,4.0,...,0.0,0.0,0.0,4.4,0.0,0.0,2.0,0.0,0.0,0.0
5,0.0,0.0,2.333333,4.25,0.0,0.0,3.25,0.000,0.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0
6,0.0,0.0,2.333333,0.00,0.0,0.0,3.25,4.500,0.0,4.0,...,0.0,0.0,0.0,4.4,0.0,0.0,2.0,0.0,0.0,0.0
7,0.0,0.0,2.333333,0.00,0.0,0.0,0.00,0.000,0.0,0.0,...,0.0,0.0,0.0,4.4,0.0,0.0,0.0,0.0,0.0,0.0
8,0.0,0.0,2.333333,4.25,0.0,0.0,3.25,4.375,0.0,4.0,...,0.0,0.0,0.0,4.4,0.0,0.0,2.0,0.0,0.0,0.0
9,0.0,0.0,2.333333,4.25,0.0,0.0,3.25,4.375,0.0,0.0,...,0.0,0.0,0.0,4.4,0.0,0.0,2.0,0.0,0.0,0.0
10,0.0,0.0,2.333333,0.00,0.0,0.0,3.25,4.500,0.0,4.0,...,0.0,0.0,0.0,4.4,0.0,0.0,2.0,0.0,0.0,0.0
11,0.0,0.0,2.333333,4.25,0.0,0.0,3.25,4.500,0.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0
12,0.0,0.0,2.333333,4.25,0.0,0.0,3.25,4.375,0.0,4.0,...,0.0,0.0,0.0,4.4,0.0,0.0,2.0,0.0,0.0,0.0
13,0.0,0.0,0.000000,4.25,0.0,0.0,0.00,0.000,0.0,4.0,...,0.0,0.0,0.0,4.2,0.0,0.0,0.0,0.0,0.0,0.0
14,0.0,0.0,2.333333,4.25,0.0,0.0,3.25,4.500,0.0,4.0,...,0.0,0.0,0.0,4.4,0.0,0.0,2.0,0.0,0.0,0.0
15,0.0,0.0,0.000000,4.25,0.0,0.0,3.25,4.375,0.0,4.0,...,0.0,0.0,0.0,4.4,0.0,0.0,2.0,0.0,0.0,0.0
16,0.0,0.0,2.333333,4.25,0.0,0.0,3.25,0.000,0.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0
17,0.0,0.0,2.333333,4.25,0.0,0.0,3.25,4.375,0.0,4.0,...,0.0,0.0,0.0,4.4,0.0,0.0,2.0,0.0,0.0,0.0
18,0.0,0.0,2.333333,0.00,0.0,0.0,3.25,4.500,0.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0
19,0.0,0.0,2.333333,4.25,0.0,0.0,3.25,4.375,0.0,4.0,...,0.0,0.0,0.0,4.4,0.0,0.0,2.0,0.0,0.0,0.0
20,0.0,0.0,2.333333,4.25,0.0,0.0,3.25,4.375,0.0,4.0,...,0.0,0.0,0.0,4.4,0.0,0.0,2.0,0.0,0.0,0.0
21,0.0,0.0,2.333333,4.25,0.0,0.0,3.25,4.375,0.0,4.0,...,0.0,0.0,0.0,4.4,0.0,0.0,0.0,0.0,0.0,0.0
22,0.0,0.0,2.333333,4.25,0.0,0.0,3.25,4.375,0.0,4.0,...,0.0,0.0,0.0,4.4,0.0,0.0,2.0,0.0,0.0,0.0
23,0.0,0.0,2.333333,4.25,0.0,0.0,3.25,4.500,0.0,4.0,...,0.0,0.0,0.0,4.4,0.0,0.0,2.0,0.0,0.0,0.0
24,0.0,0.0,2.333333,4.25,0.0,0.0,3.25,4.500,0.0,4.0,...,0.0,0.0,0.0,4.4,0.0,0.0,2.0,0.0,0.0,0.0
25,0.0,0.0,2.333333,4.25,0.0,0.0,0.00,4.500,0.0,4.0,...,0.0,0.0,0.0,4.4,0.0,0.0,2.0,0.0,0.0,0.0
26,0.0,0.0,2.333333,4.25,0.0,0.0,3.25,4.375,0.0,4.0,...,0.0,0.0,0.0,4.4,0.0,0.0,2.0,0.0,0.0,0.0
27,0.0,0.0,2.333333,4.25,0.0,0.0,3.25,4.375,0.0,4.0,...,0.0,0.0,0.0,4.4,0.0,0.0,2.0,0.0,0.0,0.0
28,0.0,0.0,2.333333,4.25,0.0,0.0,3.25,4.375,0.0,4.0,...,0.0,0.0,0.0,4.4,0.0,0.0,2.0,0.0,0.0,0.0
29,0.0,0.0,2.333333,4.25,0.0,0.0,3.25,4.375,0.0,4.0,...,0.0,0.0,0.0,4.4,0.0,0.0,2.0,0.0,0.0,0.0
30,0.0,0.0,2.333333,4.25,0.0,0.0,3.25,0.000,0.0,4.0,...,0.0,0.0,0.0,4.4,0.0,0.0,2.0,0.0,0.0,0.0
31,0.0,0.0,2.333333,4.25,0.0,0.0,3.25,4.375,0.0,4.0,...,0.0,0.0,0.0,4.4,0.0,0.0,2.0,0.0,0.0,0.0
32,0.0,0.0,2.333333,4.25,0.0,0.0,3.25,4.375,0.0,4.0,...,0.0,0.0,0.0,4.4,0.0,0.0,2.0,0.0,0.0,0.0
33,0.0,0.0,2.333333,4.25,0.0,0.0,3.25,4.375,0.0,4.0,...,0.0,0.0,0.0,4.4,0.0,0.0,2.0,0.0,0.0,0.0
34,0.0,0.0,2.333333,4.25,0.0,0.0,3.25,4.375,0.0,4.0,...,0.0,0.0,0.0,4.4,0.0,0.0,2.0,0.0,0.0,0.0
35,0.0,0.0,2.333333,4.25,0.0,0.0,3.25,4.375,0.0,4.0,...,0.0,0.0,0.0,4.4,0.0,0.0,2.0,0.0,0.0,0.0
36,0.0,0.0,2.333333,4.25,0.0,0.0,3.25,4.375,0.0,4.0,...,0.0,0.0,0.0,4.4,0.0,0.0,2.0,0.0,0.0,0.0
37,0.0,0.0,2.333333,4.25,0.0,0.0,3.25,4.375,0.0,4.0,...,0.0,0.0,0.0,4.4,0.0,0.0,2.0,0.0,0.0,0.0
38,0.0,0.0,2.333333,4.25,0.0,0.0,3.25,4.375,0.0,4.0,...,0.0,0.0,0.0,4.4,0.0,0.0,2.0,0.0,0.0,0.0
39,0.0,0.0,2.333333,4.25,0.0,0.0,3.25,4.375,0.0,4.0,...,0.0,0.0,0.0,4.4,0.0,0.0,2.0,0.0,0.0,0.0
40,0.0,0.0,2.333333,4.25,0.0,0.0,3.25,4.375,0.0,4.0,...,0.0,0.0,0.0,4.4,0.0,0.0,2.0,0.0,0.0,0.0
41,0.0,0.0,2.333333,4.25,0.0,0.0,3.25,0.000,0.0,4.0,...,0.0,0.0,0.0,4.4,0.0,0.0,2.0,0.0,0.0,0.0
42,0.0,0.0,2.333333,4.25,0.0,0.0,0.00,0.000,0.0,4.0,...,0.0,0.0,0.0,4.4,0.0,0.0,2.0,0.0,0.0,0.0
43,0.0,0.0,2.333333,4.25,0.0,0.0,3.25,4.375,0.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0
44,0.0,0.0,2.333333,4.25,0.0,0.0,3.25,0.000,0.0,4.0,...,0.0,0.0,0.0,4.4,0.0,0.0,2.0,0.0,0.0,0.0
45,0.0,0.0,0.000000,4.25,0.0,0.0,3.25,4.375,0.0,4.0,...,0.0,0.0,0.0,4.4,0.0,0.0,2.0,0.0,0.0,0.0
46,0.0,0.0,2.333333,4.25,0.0,0.0,3.25,4.375,0.0,4.0,...,0.0,0.0,0.0,4.4,0.0,0.0,2.0,0.0,0.0,0.0
47,0.0,0.0,2.333333,4.25,0.0,0.0,3.25,4.375,0.0,4.0,...,0.0,0.0,0.0,4.4,0.0,0.0,2.0,0.0,0.0,0.0
48,0.0,0.0,2.333333,4.25,0.0,0.0,3.25,4.500,0.0,4.0,...,0.0,0.0,0.0,4.4,0.0,0.0,2.0,0.0,0.0,0.0
49,0.0,0.0,0.000000,4.25,0.0,0.0,3.25,4.375,0.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0
50,0.0,0.0,2.333333,4.25,0.0,0.0,3.25,4.375,0.0,4.0,...,0.0,0.0,0.0,4.4,0.0,0.0,0.0,0.0,0.0,0.0

In [20]:
denom = 0
num = 0 
for test_user in predictions.index:
    for test_movie in predictions.columns:
        r = 1
        x = predictions.loc[test_user, test_movie]
        try:
            y = pivoted_user_test.loc[test_user,test_movie]
        except KeyError:
            r = 0
        denom += r
        num += r * np.abs(x-y)
print(num/denom)

1.34055328467